// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": [[ marshal .Schemes ]],
    "swagger": "2.0",
    "info": {
        "description": "[[escape .Description]]",
        "title": "[[.Title]]",
        "contact": {},
        "version": "[[.Version]]"
    },
    "host": "[[.Host]]",
    "basePath": "[[.BasePath]]",
    "paths": {
        "/api/v1/admin/admins": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "列出当前具备管理权限的账号。名单真源在 Redis。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端"
                ],
                "summary": "管理员名单",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AdminListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "把已注册用户加入管理员名单，并撤销其现有会话（旧令牌的 role 已过时，需重新登录）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端"
                ],
                "summary": "提升为管理员",
                "parameters": [
                    {
                        "description": "目标用户",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminUserIDReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AdminMutationResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或用户不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/admins/{user_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "把用户移出管理员名单，并撤销其现有会话。服务端强制 403 读的就是这份名单，因此立即生效。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端"
                ],
                "summary": "撤销管理员",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "目标用户 ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AdminMutationResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/mail-templates": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "列出全部邮件模板；每个模板附带它用到的变量名，便于管理端提示。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端-邮件"
                ],
                "summary": "邮件模板列表",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MailModelListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "主题与正文都支持 {{变量}} 占位符；括号不成对会被拒绝（那是会静默发出错信的错误）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端-邮件"
                ],
                "summary": "新建邮件模板",
                "parameters": [
                    {
                        "description": "模板内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.MailTemplateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MailModelResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或模板名/类型重复",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/mail-templates/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端-邮件"
                ],
                "summary": "更新邮件模板",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "模板 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "模板内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.MailTemplateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MailModelResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误、模板不存在或名称重复",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "只删模板，不动已发出的邮件记录——记录是审计凭据，不该因为模板被删就消失。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端-邮件"
                ],
                "summary": "删除邮件模板",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "模板 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "400": {
                        "description": "模板不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/mails": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按发送时间倒序分页。可选 keyword（主题/收件人模糊匹配）与 from/to（日期，含端点）过滤；total 为过滤后的总数。只返回记录元信息，不返回正文。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端-邮件"
                ],
                "summary": "发信记录",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从 1 开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页条数，最大 100",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "模糊搜索主题与收件人邮箱，最长 100",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起始日期 YYYY-MM-DD（含当天）",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD（含当天）",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MailRecordListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "日期格式错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/mails/batch-delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员清理记录用；返回实际删除的行数，ids 中已不存在的 id 会被跳过。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端-邮件"
                ],
                "summary": "批量删除发信记录",
                "parameters": [
                    {
                        "description": "待删除的记录 id 列表",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.MailBatchDeleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MailBatchDeleteResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/mails/send": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "变量不传也行：服务端会用收件人资料（姓名/邮箱/班级/方向/学号/轮次）预填，请求里的同键覆盖。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端-邮件"
                ],
                "summary": "按 userID 发送邮件",
                "parameters": [
                    {
                        "description": "发送参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendMailToUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MailSendResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误、模板不存在、缺少变量或用户没有邮箱",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/mails/send-bulk": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "逐条独立投递，单个失败不影响其他收件人；响应里分别给出成功与失败清单。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端-邮件"
                ],
                "summary": "群发邮件（同一模板，逐个替换内容）",
                "parameters": [
                    {
                        "description": "群发参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendMailBulkReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（含逐条结果）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MailBulkSendResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误、模板不存在或收件人超过上限",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/mails/send-by-email": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用于发给还没注册的报名者；邮箱能对上已注册用户时会按用户记录。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端-邮件"
                ],
                "summary": "按邮箱地址发送邮件",
                "parameters": [
                    {
                        "description": "发送参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendMailToEmailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MailSendResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误、模板不存在或缺少变量",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页读取已注册用户，并标注其当前是否为管理员。响应不含密码哈希。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理端"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从 1 开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页条数，最大 100",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AdminUserListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "403": {
                        "description": "非管理员",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "通过用户名**或邮箱** + 密码登录，返回双令牌（access_token + refresh_token）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回双令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误（不区分二者）",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/logout": {
            "post": {
                "description": "退出登录接口（需要 access token 和 refresh token）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "用户退出登录接口",
                "parameters": [
                    {
                        "description": "退出登录请求参数（refresh_token）",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RefreshReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "退出登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "角色由服务端**现查 Redis 管理员名单**得到，而不是回显令牌里的快照，",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "获取当前登录用户",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MeResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未认证、令牌失效或账号已不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "只改令牌本人的资料，body 不接受 user_id 等目标参数（未知键直接忽略）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "更新本人资料",
                "parameters": [
                    {
                        "description": "资料字段补丁",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateMePatch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新后的完整资料",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MeResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "401": {
                        "description": "未认证、令牌失效或账号已不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/refresh": {
            "post": {
                "description": "使用 refresh token 获取新的一对令牌，旧令牌立即失效（单端登录）。不返回用户 ID。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新令牌请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RefreshReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回新的双令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.RefreshResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "401": {
                        "description": "refresh token 无效或已失效",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "description": "注册新用户，返回双令牌。邮箱唯一；必须先通过 /send-verify-code 取得验证码。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回双令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误、邮箱已注册或验证码错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/send-verify-code": {
            "post": {
                "description": "发送邮箱验证码，5 分钟内有效、只能使用一次、猜错 5 次即作废。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "发送验证码接口",
                "parameters": [
                    {
                        "description": "验证目标",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.VerifyCodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "发送验证码成功",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "429": {
                        "description": "请求过于频繁",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "不检查任何外部依赖，供容器存活探针使用。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查（存活）",
                "responses": {
                    "200": {
                        "description": "服务存活",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "探活 PostgreSQL 与 Redis；任一不可用返回 503。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查（就绪）",
                "responses": {
                    "200": {
                        "description": "依赖均可用",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "503": {
                        "description": "依赖不可用",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.AdminUserIDReq": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "request.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.MailBatchDeleteReq": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "maxItems": 500,
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "request.MailRecipientReq": {
            "type": "object",
            "required": [
                "to_user_id"
            ],
            "properties": {
                "to_user_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "vars": {
                    "$ref": "#/definitions/request.MailVars"
                }
            }
        },
        "request.MailTemplateReq": {
            "type": "object",
            "required": [
                "mail_model",
                "name",
                "title",
                "type"
            ],
            "properties": {
                "mail_example": {
                    "type": "string",
                    "maxLength": 5000
                },
                "mail_model": {
                    "type": "string",
                    "maxLength": 20000,
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "type": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 1
                }
            }
        },
        "request.MailVars": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "request.RefreshReq": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "request.RegisterReq": {
            "type": "object",
            "required": [
                "code",
                "email",
                "name",
                "password"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 6,
                    "minLength": 6
                },
                "email": {
                    "type": "string",
                    "maxLength": 50
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                }
            }
        },
        "request.SendMailBulkReq": {
            "type": "object",
            "required": [
                "recipients",
                "template_id"
            ],
            "properties": {
                "recipients": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/request.MailRecipientReq"
                    }
                },
                "template_id": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "request.SendMailToEmailReq": {
            "type": "object",
            "required": [
                "email",
                "template_id"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 50
                },
                "template_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "vars": {
                    "$ref": "#/definitions/request.MailVars"
                }
            }
        },
        "request.SendMailToUserReq": {
            "type": "object",
            "required": [
                "template_id",
                "to_user_id"
            ],
            "properties": {
                "template_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "to_user_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "vars": {
                    "$ref": "#/definitions/request.MailVars"
                }
            }
        },
        "request.UpdateMePatch": {
            "type": "object",
            "properties": {
                "class": {
                    "description": "班级；null 清除，缺省不动",
                    "type": "string",
                    "example": "物联网工程 2301"
                },
                "direction": {
                    "description": "方向；null/空串清除，缺省不动",
                    "type": "string",
                    "enum": [
                        "front-end",
                        "back-end",
                        "agent",
                        "all",
                        "game",
                        "other"
                    ],
                    "example": "front-end"
                },
                "qq": {
                    "description": "QQ；null 清除，缺省不动",
                    "type": "string",
                    "example": "1044696157"
                },
                "student_id": {
                    "description": "学号；null 清除（0 视为未填），缺省不动",
                    "type": "integer",
                    "example": 2023114514
                }
            }
        },
        "request.VerifyCodeReq": {
            "type": "object",
            "required": [
                "verifier",
                "verifier_type"
            ],
            "properties": {
                "verifier": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6
                },
                "verifier_type": {
                    "type": "string",
                    "enum": [
                        "email",
                        "phone"
                    ]
                }
            }
        },
        "response.AdminListResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AdminUserResp"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.AdminMutationResp": {
            "type": "object",
            "properties": {
                "is_admin": {
                    "type": "boolean"
                },
                "session_revoked": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "response.AdminUserListResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AdminUserResp"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.AdminUserResp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "detail": {
                    "description": "Detail 只读资料（issue #57）：管理员能看到完整信息，但改不了——\n编辑入口只有本人的 PUT /me。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.UserProfileDetail"
                        }
                    ]
                },
                "is_admin": {
                    "description": "IsAdmin 由 Redis 名单现算，方便管理端直接标注\"当前是不是管理员\"",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "response.LoginResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "response.MailBatchDeleteResp": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "integer"
                }
            }
        },
        "response.MailBulkSendResp": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MailSendFailure"
                    }
                },
                "sent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MailSendResp"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.MailModelListResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MailModelResp"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.MailModelResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "mail_example": {
                    "type": "string"
                },
                "mail_model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "variables": {
                    "description": "Variables 模板里用到的变量名，管理端据此提示\"这封模板需要哪些变量\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.MailRecordListResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MailRecordResp"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.MailRecordResp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "from_user_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "to_email": {
                    "type": "string"
                },
                "to_user_id": {
                    "type": "integer"
                }
            }
        },
        "response.MailSendFailure": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                },
                "to_email": {
                    "type": "string"
                },
                "to_user_id": {
                    "type": "integer"
                }
            }
        },
        "response.MailSendResp": {
            "type": "object",
            "properties": {
                "title": {
                    "description": "Title 是渲染之后的实际主题（不是模板原文），便于确认变量替换是否正确",
                    "type": "string"
                },
                "to_email": {
                    "type": "string"
                },
                "to_user_id": {
                    "type": "integer"
                }
            }
        },
        "response.MeResp": {
            "type": "object",
            "properties": {
                "detail": {
                    "$ref": "#/definitions/response.UserProfileDetail"
                },
                "name": {
                    "description": "Name 是姓名（domain.User.Name），与 username 同源但语义独立：\n前端个人设置页把它当只读展示项。",
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.RefreshResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "response.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务码：0 成功，非 0 失败",
                    "type": "integer"
                },
                "data": {
                    "description": "业务数据"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "response.UserProfileDetail": {
            "type": "object",
            "properties": {
                "class": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "qq": {
                    "type": "string"
                },
                "student_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "登录得到的 access_token。Swagger UI 的 Authorize 里只填 token 本身，前缀由 UI 补。",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "iot-pillot API",
	Description:      "IoT 全栈开发工作室的招新管理后台 API。\n统一响应体是 {code, message, data}；除公开端点（注册/登录/发码/刷新/登出）外都需要 Authorization: Bearer <access_token>。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "[[",
	RightDelim:       "]]",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
