// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/IOT-devstudio/iot-pillot/apps/api/internal/config"
	"github.com/IOT-devstudio/iot-pillot/apps/api/internal/handler"
	"github.com/IOT-devstudio/iot-pillot/apps/api/internal/repository"
	"github.com/IOT-devstudio/iot-pillot/apps/api/internal/service"
	"github.com/IOT-devstudio/iot-pillot/apps/api/internal/utils"
)

// Injectors from wire.go:

func InitializeApp() (*handler.Router, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	healthHandler := handler.NewHealthHandler()
	db, cleanup, err := repository.ProvideDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepo := repository.NewUserRepo(db)
	client := utils.ConnectRedis(configConfig)
	tokenManager := utils.NewTokenManager(client, configConfig)
	mailManager := utils.NewMailManager(configConfig, client)
	codeManager := utils.NewCodeManager(client, mailManager)
	adminStore := utils.NewAdminStore(client)
	authUseCase := service.NewAuthUseCase(userRepo, tokenManager, codeManager, adminStore)
	authHandler := handler.NewAuthHandler(authUseCase)
	adminUseCase, err := provideAdminUseCase(userRepo, adminStore, tokenManager, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	adminHandler := handler.NewAdminHandler(adminUseCase)
	mailModelRepo := repository.NewMailModelRepo(db)
	mailRepo := repository.NewMailRepo(db)
	mailUseCase := service.NewMailUseCase(mailModelRepo, mailRepo, userRepo, mailManager)
	mailHandler := handler.NewMailHandler(mailUseCase)
	router := handler.NewRouter(configConfig, healthHandler, authHandler, adminHandler, mailHandler, tokenManager, adminStore)
	return router, func() {
		cleanup()
	}, nil
}
