// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/IOT-devstudio/iot-pillot/apps/api/internal/config"
	"github.com/IOT-devstudio/iot-pillot/apps/api/internal/handler"
)

// Injectors from wire.go:

func InitializeApp() (*handler.Router, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	healthHandler := handler.NewHealthHandler()
	router := handler.NewRouter(configConfig, healthHandler)
	return router, func() {
	}, nil
}
